# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/*'
      - 'docs/**'
      - 'book.json'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: build
      run: |
        echo "---------- node-version `node -v` ----------"
        npm i
        echo "---------- npm install ok ----------"
        npm run build
        npm run build
        echo "---------- build ok ----------"
    - name: download and replace # 下载现有文件，替换
      run: |
        git clone https://github.com/gaoxiaoshi/base.web-guide.funny-share.com.git
        echo "---------- git clone ok ----------"
        cp -r ./_book/* ./base.web-guide.funny-share.com ## 用最新构建出来的文件，替换现有的
        echo "---------- replace ok ----------"
    - name: upload # 上传文件
      run: |
        cd ./base.web-guide.funny-share.com
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        echo "---------- begin git status ----------"
        echo `git status`
        echo "---------- end git status ----------"
        git add .
        git commit -m "update by github actions"
        git push origin main
