- name: Publish Gitbook
  # You may pin to the exact commit or the version.
  # uses: tuliren/publish-gitbook@f3830e3fc7bf059e0501c5ed535d97b2aa181e2e
  uses: tuliren/publish-gitbook@v1.0.0
  with:
    # Github token for the repo
    github_token: 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
